#!/bin/bash
set -Eeo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# TODO: This will only get the first line of a TODO.  Reimplement this sanely?
grep \
  -R \
  -E \
  -e '^\s*[#;]\s*TODO:?\s*(\S.*)' \
  "$DIR" \
  --exclude-dir="$DIR/cache" \
  --line-number \
| sed -re 's@^([^:]+:[0-9]+:)[^:]+:\s+(.*)$@\1 \2@g'
exit $?

# TODO: Ensure DNS servers can start without a running DNS server.  Bootstraps.

# TODO: I need a way to allow a build (in a chroot) to request the build
#       system to request a dependency build which will need to start outside
#       of the chroot context, as it will require a new root.


# TODO: ssh dev keys package is fubar due to not packaging /root

# TODO: need to set up https access in gitzebo for go get to work

# TODO: need to figure out how to package git parameters (user.name and email)
#       (/root/.gitconfig)

# TODO: move Selenium bank info project into Git
# TODO: move Selenium bank info project into buildsystem
# TODO: move Selenium bank info project into container

# TODO: move certificate authority project into buildsystem
# TODO: move certificate authority project into container
# TODO: add web interface to certificate authority project
